# Generated by Django 5.0.2 on 2024-02-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200)),
                ('n_memory', models.IntegerField()),
                ('n_cpu', models.IntegerField()),
                ('gpu_type', models.CharField(max_length=10)),
                ('n_mem', models.IntegerField()),
            ],
        ),
    ]
