# Generated by Django 5.0.2 on 2024-02-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cloudselect'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudselect',
            name='app_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cloudselect',
            name='password',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cloudselect',
            name='tenant_id',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
