# Generated by Django 5.0.2 on 2024-02-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_cloudselect_app_id_cloudselect_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cloudConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_type', models.CharField(max_length=20)),
                ('n_acc', models.IntegerField()),
                ('n_cpus', models.IntegerField()),
                ('n_memory', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='userInput',
        ),
    ]
