# Generated by Django 5.0.2 on 2024-03-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_cloudconfigmodel_delete_userinput'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloudconfigmodel',
            old_name='acc_type',
            new_name='checkpoint_bucket',
        ),
        migrations.RemoveField(
            model_name='cloudconfigmodel',
            name='n_acc',
        ),
        migrations.RemoveField(
            model_name='cloudconfigmodel',
            name='n_cpus',
        ),
        migrations.RemoveField(
            model_name='cloudconfigmodel',
            name='n_memory',
        ),
        migrations.AddField(
            model_name='cloudconfigmodel',
            name='accelerator',
            field=models.CharField(blank=True, default='A100-40GB:2', max_length=15),
        ),
        migrations.AddField(
            model_name='cloudconfigmodel',
            name='checkpoint_store',
            field=models.CharField(blank=True, default='S3', max_length=20),
        ),
        migrations.AddField(
            model_name='cloudconfigmodel',
            name='finetune_data',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cloudconfigmodel',
            name='hf_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cloudconfigmodel',
            name='model_type',
            field=models.CharField(blank=True, default='llama', max_length=50),
        ),
        migrations.AddField(
            model_name='cloudconfigmodel',
            name='region',
            field=models.CharField(blank=True, default='us-central1', max_length=15),
        ),
        migrations.AddField(
            model_name='cloudconfigmodel',
            name='train_type',
            field=models.CharField(blank=True, default='full_fine_tuning', max_length=50),
        ),
        migrations.AddField(
            model_name='cloudconfigmodel',
            name='wandb_api_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cloudconfigmodel',
            name='zone',
            field=models.CharField(blank=True, default='a', max_length=10),
        ),
        migrations.AlterField(
            model_name='cloudselect',
            name='cloud_name',
            field=models.CharField(blank=True, default='Azure', max_length=20),
        ),
    ]
