# Generated by Django 5.0.2 on 2024-03-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_acc_type_cloudconfigmodel_checkpoint_bucket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudconfigmodel',
            name='name',
            field=models.CharField(blank=True, default='my_model', max_length=50),
        ),
        migrations.AlterField(
            model_name='cloudselect',
            name='cloud_name',
            field=models.CharField(blank=True, default='azure', max_length=20),
        ),
    ]
